import { createHash } from "node:crypto";
import { existsSync, readFileSync, writeFileSync, watch } from "node:fs";
import { fileURLToPath } from "node:url";
import { createContext, runInContext } from "node:vm";

const root = new URL("../", import.meta.url);
const sources = ["sandbox-content.js", "sandbox-viewer.js"];

export function buildSha256(content) {
  return `sha256-${createHash("sha256").update(content, "utf8").digest("base64")}`;
}

function writeChanged(path, content) {
  if (existsSync(path) && readFileSync(path, "utf8") === content) return;
  writeFileSync(path, content);
}

export function buildSandboxCsp(projectRoot = root) {
  // Evaluate the trusted declarations rather than hashing JS source text:
  // template literals, escapes and CRLF must match the browser's actual strings.
  const context = createContext({});
  for (const name of sources) {
    runInContext(readFileSync(new URL(`src/${name}`, projectRoot), "utf8"), context, { timeout: 1000 });
  }
  const styleHash = buildSha256(runInContext("SANDBOX_STYLE", context));
  const scriptHash = buildSha256(runInContext("SANDBOX_VIEWER_SCRIPT", context));
  const base = JSON.parse(readFileSync(new URL("src-tauri/tauri.conf.json", projectRoot), "utf8"));
  let csp = base.app.security.csp;
  for (const [directive, hash] of [["style-src", styleHash], ["script-src", scriptHash]]) {
    const pattern = new RegExp(`(^|;\\s*)${directive}(?=\\s|;|$)([^;]*)`);
    if (!pattern.test(csp)) throw new Error(`Missing ${directive} in tauri.conf.json`);
    csp = csp.replace(pattern, (_, prefix, values) => `${prefix}${directive}${values.trimEnd()} '${hash}'`);
  }
  const hashes = `// Generated by scripts/build-csp.mjs. Do not edit.\nconst SANDBOX_STYLE_HASH = ${JSON.stringify(styleHash)};\nconst SANDBOX_VIEWER_SCRIPT_HASH = ${JSON.stringify(scriptHash)};\n`;
  const config = JSON.stringify({ app: { security: { csp } } }, null, 2) + "\n";
  writeChanged(new URL("src/sandbox-hashes.generated.js", projectRoot), hashes);
  // Tauri automatically loads and reloads the matching platform configuration.
  for (const platform of ["windows", "linux", "macos"]) {
    writeChanged(new URL(`src-tauri/tauri.${platform}.conf.json`, projectRoot), config);
  }
  return { styleHash, scriptHash, csp };
}

export function watchSandboxCsp(projectRoot = root, onError = console.error) {
  let timer;
  const schedule = () => {
    clearTimeout(timer);
    timer = setTimeout(() => {
      try { buildSandboxCsp(projectRoot); }
      catch (error) { onError(error); }
    }, 100);
  };
  const watchers = [
    watch(new URL("src/", projectRoot), (_, name) => {
      if (!name || sources.includes(String(name))) schedule();
    }),
    watch(new URL("src-tauri/", projectRoot), (_, name) => {
      if (!name || String(name) === "tauri.conf.json") schedule();
    }),
  ];
  return () => { clearTimeout(timer); for (const watcher of watchers) watcher.close(); };
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  buildSandboxCsp();
  if (process.argv.includes("--watch")) {
    watchSandboxCsp(root, (error) => console.error(`Could not regenerate sandbox CSP: ${error.message}`));
  }
}
